ALTER PROFILE "DEFAULT" LIMIT
  PASSWORD_LIFE_TIME UNLIMITED  -- important to set to UNLIMITED
  PASSWORD_GRACE_TIME UNLIMITED; -- important to set to UNLIMITED


DROP USER CONFIG CASCADE;

CREATE USER CONFIG
  IDENTIFIED BY CONFIG
  DEFAULT TABLESPACE &ts
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for CONFIG 
  GRANT RESOURCE TO CONFIG;
  GRANT CONNECT TO CONFIG;
  ALTER USER CONFIG DEFAULT ROLE ALL;
  -- 4 System Privileges for CONFIG 
  GRANT CREATE PROCEDURE TO CONFIG;
  GRANT UNLIMITED TABLESPACE TO CONFIG;
  GRANT EXECUTE ANY PROCEDURE TO CONFIG;
  GRANT CREATE ANY SYNONYM TO CONFIG;
  -- 5 Object Privileges for CONFIG 
    GRANT EXECUTE ON SYS.DBMS_ALERT TO CONFIG;
    GRANT SELECT ON SYS.V_$SESSION TO CONFIG;

DROP USER CIS_HMI_PA CASCADE;

CREATE USER CIS_HMI_PA
  IDENTIFIED BY VALUES 'A34597ADC60EA58D'
  DEFAULT TABLESPACE &TABLESPACE
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for CIS_HMI_PA 
  GRANT CONNECT TO CIS_HMI_PA;
  GRANT RESOURCE TO CIS_HMI_PA;
  ALTER USER CIS_HMI_PA DEFAULT ROLE ALL;
  --  System Privileges for CIS_HMI_PA 
  GRANT ADMINISTER DATABASE TRIGGER TO CIS_HMI_PA;
  GRANT ALTER SYSTEM TO CIS_HMI_PA;
  GRANT CREATE ANY SYNONYM TO CIS_HMI_PA;
  GRANT CREATE PROCEDURE TO CIS_HMI_PA;
  GRANT EXECUTE ANY PROCEDURE TO CIS_HMI_PA;
  GRANT UNLIMITED TABLESPACE TO CIS_HMI_PA;
  -- Object Privileges for COMM
    GRANT SELECT ON SYS.DBA_JOBS TO CIS_HMI_PA;
    GRANT SELECT ON SYS.DBA_JOBS_RUNNING TO CIS_HMI_PA;
    GRANT SELECT ON SYS.DBA_OBJECTS TO CIS_HMI_PA;
    GRANT SELECT ON SYS.DBA_VIEWS TO CIS_HMI_PA;
    GRANT SELECT ON SYS.DBA_WAITERS TO CIS_HMI_PA;
    GRANT SELECT ON SYS.DBMS_ALERT_INFO TO CIS_HMI_PA;
    GRANT EXECUTE ON SYS.DBMS_SYSTEM TO CIS_HMI_PA;
    GRANT SELECT ON SYS.GV_$INSTANCE TO CIS_HMI_PA;
    GRANT SELECT ON SYS.GV_$LOCK TO CIS_HMI_PA;
    GRANT SELECT ON SYS.GV_$LOCKED_OBJECT TO CIS_HMI_PA;
    GRANT SELECT ON SYS.GV_$SESSION TO CIS_HMI_PA;
    GRANT SELECT ON SYS.JOB$ TO CIS_HMI_PA;
    GRANT SELECT ON SYS.V_$DATABASE TO CIS_HMI_PA;
    GRANT SELECT ON SYS.V_$MYSTAT TO CIS_HMI_PA;
    GRANT SELECT ON SYS.V_$PROCESS TO CIS_HMI_PA;
    GRANT SELECT ON SYS.V_$SESSION TO CIS_HMI_PA;


DROP USER COMM CASCADE;

CREATE USER COMM
  IDENTIFIED BY VALUES '184268C92F79F3ED'
  DEFAULT TABLESPACE &TABLESPACE
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for COMM 
  GRANT CONNECT TO COMM;
  GRANT RESOURCE TO COMM;
  ALTER USER COMM DEFAULT ROLE ALL;
  -- 4 System Privileges for COMM 
  GRANT CREATE ANY SYNONYM TO COMM;
  GRANT DROP ANY SYNONYM TO COMM;
  GRANT EXECUTE ANY PROCEDURE TO COMM;
  GRANT UNLIMITED TABLESPACE TO COMM;
  -- Object Privileges for COMM 
    GRANT EXECUTE ON SYS.DBMS_SYSTEM TO COMM;
    GRANT SELECT ON SYS.V_$MYSTAT TO COMM;
    GRANT SELECT ON SYS.V_$SESSION TO COMM;
    GRANT EXECUTE ON SYS.DBMS_ALERT TO COMM;
 

DROP USER MAIN CASCADE;

CREATE USER MAIN
  IDENTIFIED BY VALUES '5ACF76541EE8B18F'
  DEFAULT TABLESPACE &TABLESPACE
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for MAIN 
  GRANT CONNECT TO MAIN;
  GRANT RESOURCE TO MAIN;
  ALTER USER MAIN DEFAULT ROLE ALL;
  -- 8 System Privileges for MAIN 
  GRANT ADMINISTER DATABASE TRIGGER TO MAIN;
  GRANT ALTER SYSTEM TO MAIN;
  GRANT CREATE ANY DIRECTORY TO MAIN;
  GRANT CREATE ANY SYNONYM TO MAIN;
  GRANT CREATE DATABASE LINK TO MAIN;
  GRANT CREATE PROCEDURE TO MAIN;
  GRANT DROP ANY DIRECTORY TO MAIN;
  GRANT UNLIMITED TABLESPACE TO MAIN;
  GRANT ALTER ANY MATERIALIZED VIEW TO MAIN;
  GRANT CREATE ANY MATERIALIZED VIEW TO MAIN;
  GRANT CREATE ANY TABLE TO MAIN;
  GRANT ALTER ANY TABLE TO MAIN;
  -- Object Privileges for MAIN 
    GRANT SELECT ON SYS.DBA_JOBS TO MAIN;
    GRANT SELECT ON SYS.DBA_JOBS_RUNNING TO MAIN;
    GRANT SELECT ON SYS.DBA_OBJECTS TO MAIN;
    GRANT SELECT ON SYS.DBA_VIEWS TO MAIN;
    GRANT SELECT ON SYS.DBA_WAITERS TO MAIN;
    GRANT SELECT ON SYS.DBMS_ALERT_INFO TO MAIN;
    GRANT EXECUTE ON SYS.DBMS_SYSTEM TO MAIN;
    GRANT SELECT ON SYS.GV_$INSTANCE TO MAIN;
    GRANT SELECT ON SYS.GV_$LOCK TO MAIN;
    GRANT SELECT ON SYS.GV_$LOCKED_OBJECT TO MAIN;
    GRANT SELECT ON SYS.GV_$SESSION TO MAIN;
    GRANT SELECT ON SYS.JOB$ TO MAIN;
    GRANT SELECT ON SYS.V_$DATABASE TO MAIN;
    GRANT SELECT ON SYS.V_$MYSTAT TO MAIN;
    GRANT SELECT ON SYS.V_$PROCESS TO MAIN;
    GRANT SELECT ON SYS.V_$SESSION TO MAIN;
    GRANT EXECUTE ON SYS.DBMS_ALERT TO MAIN; 
    GRANT EXECUTE ON SYS.DBMS_LOCK TO MAIN; 
    grant execute on dbms_pipe to MAIN;
    grant execute on dbms_job to MAIN;
    GRANT EXECUTE, DEBUG ON SYS.dbms_flashback TO MAIN;
    

DROP USER STOPPAGE CASCADE;

CREATE USER STOPPAGE
  IDENTIFIED BY VALUES '77019D0FE6E69024'
  DEFAULT TABLESPACE &TABLESPACE
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for STOPPAGE 
  GRANT CONNECT TO STOPPAGE;
  GRANT RESOURCE TO STOPPAGE;
  ALTER USER STOPPAGE DEFAULT ROLE ALL;
  -- 6 System Privileges for STOPPAGE 
  GRANT ADMINISTER DATABASE TRIGGER TO STOPPAGE;
  GRANT ALTER SYSTEM TO STOPPAGE;
  GRANT CREATE ANY SYNONYM TO STOPPAGE;
  GRANT CREATE PROCEDURE TO STOPPAGE;
  GRANT EXECUTE ANY PROCEDURE TO STOPPAGE;
  GRANT UNLIMITED TABLESPACE TO STOPPAGE;
  GRANT CREATE ANY MATERIALIZED VIEW TO STOPPAGE;
  GRANT CREATE ANY TABLE TO STOPPAGE;
  GRANT ALTER ANY TABLE TO STOPPAGE;
  -- Object Privileges for STOPPAGE 
    GRANT SELECT ON SYS.DBA_JOBS TO STOPPAGE;
    GRANT SELECT ON SYS.DBA_JOBS_RUNNING TO STOPPAGE;
    GRANT SELECT ON SYS.DBA_OBJECTS TO STOPPAGE;
    GRANT SELECT ON SYS.DBA_VIEWS TO STOPPAGE;
    GRANT SELECT ON SYS.DBA_WAITERS TO STOPPAGE;
    GRANT SELECT ON SYS.DBMS_ALERT_INFO TO STOPPAGE;
    GRANT EXECUTE ON SYS.DBMS_SYSTEM TO STOPPAGE;
    GRANT SELECT ON SYS.GV_$INSTANCE TO STOPPAGE;
    GRANT SELECT ON SYS.GV_$LOCK TO STOPPAGE;
    GRANT SELECT ON SYS.GV_$LOCKED_OBJECT TO STOPPAGE;
    GRANT SELECT ON SYS.GV_$SESSION TO STOPPAGE;
    GRANT SELECT ON SYS.JOB$ TO STOPPAGE;
    GRANT SELECT ON SYS.V_$DATABASE TO STOPPAGE;
    GRANT SELECT ON SYS.V_$MYSTAT TO STOPPAGE;
    GRANT SELECT ON SYS.V_$PROCESS TO STOPPAGE;
    GRANT SELECT ON SYS.V_$SESSION TO STOPPAGE;

DROP USER STRACK CASCADE;

CREATE USER STRACK
  IDENTIFIED BY VALUES '05C0AD3F13340C1A'
  DEFAULT TABLESPACE &TABLESPACE
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for STRACK 
  GRANT CONNECT TO STRACK;
  GRANT RESOURCE TO STRACK;
  ALTER USER STRACK DEFAULT ROLE ALL;
  -- 6 System Privileges for STRACK 
  GRANT ADMINISTER DATABASE TRIGGER TO STRACK;
  GRANT ALTER SYSTEM TO STRACK;
  GRANT CREATE ANY SYNONYM TO STRACK;
  GRANT CREATE PROCEDURE TO STRACK;
  GRANT EXECUTE ANY PROCEDURE TO STRACK;
  GRANT UNLIMITED TABLESPACE TO STRACK;
  -- Object Privileges for STRACK 
    GRANT SELECT ON SYS.DBA_JOBS TO STRACK;
    GRANT SELECT ON SYS.DBA_JOBS_RUNNING TO STRACK;
    GRANT SELECT ON SYS.DBA_OBJECTS TO STRACK;
    GRANT SELECT ON SYS.DBA_VIEWS TO STRACK;
    GRANT SELECT ON SYS.DBA_WAITERS TO STRACK;
    GRANT SELECT ON SYS.DBMS_ALERT_INFO TO STRACK;
    GRANT EXECUTE ON SYS.DBMS_SYSTEM TO STRACK;
    GRANT SELECT ON SYS.GV_$INSTANCE TO STRACK;
    GRANT SELECT ON SYS.GV_$LOCK TO STRACK;
    GRANT SELECT ON SYS.GV_$LOCKED_OBJECT TO STRACK;
    GRANT SELECT ON SYS.GV_$SESSION TO STRACK;
    GRANT SELECT ON SYS.JOB$ TO STRACK;
    GRANT SELECT ON SYS.V_$DATABASE TO STRACK;
    GRANT SELECT ON SYS.V_$MYSTAT TO STRACK;
    GRANT SELECT ON SYS.V_$PROCESS TO STRACK;
    GRANT SELECT ON SYS.V_$SESSION TO STRACK;

----------------------------------------------------------	
-------------------L2admin--------------------------------	
----------------------------------------------------------	
DROP USER L2ADMIN CASCADE;

CREATE USER L2ADMIN
  IDENTIFIED BY L2ADMIN
  DEFAULT TABLESPACE &TABLESPACE
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 24 Roles for L2ADMIN 
  GRANT DBA TO L2ADMIN WITH ADMIN OPTION;
  GRANT RECOVERY_CATALOG_OWNER TO L2ADMIN WITH ADMIN OPTION;
  GRANT EXECUTE_CATALOG_ROLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT DELETE_CATALOG_ROLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT LOGSTDBY_ADMINISTRATOR TO L2ADMIN WITH ADMIN OPTION;
  GRANT HS_ADMIN_SELECT_ROLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT HS_ADMIN_ROLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT EXP_FULL_DATABASE TO L2ADMIN WITH ADMIN OPTION;
  GRANT IMP_FULL_DATABASE TO L2ADMIN WITH ADMIN OPTION;
  GRANT DBFS_ROLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT DATAPUMP_EXP_FULL_DATABASE TO L2ADMIN WITH ADMIN OPTION;
  GRANT OEM_MONITOR TO L2ADMIN WITH ADMIN OPTION;
  GRANT DATAPUMP_IMP_FULL_DATABASE TO L2ADMIN WITH ADMIN OPTION;
  GRANT SELECT_CATALOG_ROLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT AQ_ADMINISTRATOR_ROLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT OEM_ADVISOR TO L2ADMIN WITH ADMIN OPTION;
  GRANT CONNECT TO L2ADMIN WITH ADMIN OPTION;
  GRANT AQ_USER_ROLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT SCHEDULER_ADMIN TO L2ADMIN WITH ADMIN OPTION;
  GRANT GATHER_SYSTEM_STATISTICS TO L2ADMIN WITH ADMIN OPTION;
  GRANT HS_ADMIN_EXECUTE_ROLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT WM_ADMIN_ROLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT RESOURCE TO L2ADMIN WITH ADMIN OPTION;
  GRANT ADM_PARALLEL_EXECUTE_TASK TO L2ADMIN WITH ADMIN OPTION;
  ALTER USER L2ADMIN DEFAULT ROLE ALL;
  -- 206 System Privileges for L2ADMIN 
  GRANT FLASHBACK ARCHIVE ADMINISTER TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY CUBE BUILD PROCESS TO L2ADMIN WITH ADMIN OPTION;
  GRANT INSERT ANY CUBE DIMENSION TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ASSEMBLY TO L2ADMIN WITH ADMIN OPTION;
  GRANT EXECUTE ANY CLASS TO L2ADMIN WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'L2ADMIN',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'L2ADMIN',
  GRANT_OPTION => TRUE);
END;
/
  GRANT FLASHBACK ANY TABLE TO L2ADMIN WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'L2ADMIN',
  ADMIN_OPTION => TRUE);
END;
/
  GRANT EXECUTE ANY OPERATOR TO L2ADMIN WITH ADMIN OPTION;
  GRANT EXECUTE ANY LIBRARY TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY LIBRARY TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER PROFILE TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP PUBLIC SYNONYM TO L2ADMIN WITH ADMIN OPTION;
  GRANT INSERT ANY TABLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT COMMENT ANY TABLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE TABLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER DATABASE LINK TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY CUBE TO L2ADMIN WITH ADMIN OPTION;
  GRANT COMMENT ANY MINING MODEL TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE MINING MODEL TO L2ADMIN WITH ADMIN OPTION;
  GRANT ADMINISTER SQL TUNING SET TO L2ADMIN WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'L2ADMIN',
  GRANT_OPTION => TRUE);
END;
/
  GRANT IMPORT FULL DATABASE TO L2ADMIN WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'L2ADMIN',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'L2ADMIN',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'L2ADMIN',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'L2ADMIN',
  ADMIN_OPTION => TRUE);
END;
/
  GRANT DROP ANY DIMENSION TO L2ADMIN WITH ADMIN OPTION;
  GRANT QUERY REWRITE TO L2ADMIN WITH ADMIN OPTION;
  GRANT UNDER ANY VIEW TO L2ADMIN WITH ADMIN OPTION;
  GRANT UNDER ANY TYPE TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY TYPE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY TYPE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE TYPE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY MATERIALIZED VIEW TO L2ADMIN WITH ADMIN OPTION;
  GRANT FORCE ANY TRANSACTION TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE SEQUENCE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE VIEW TO L2ADMIN WITH ADMIN OPTION;
  GRANT DELETE ANY TABLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ROLLBACK SEGMENT TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER USER TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER SYSTEM TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE CUBE BUILD PROCESS TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY MEASURE FOLDER TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE MEASURE FOLDER TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY CUBE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY CUBE DIMENSION TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY ASSEMBLY TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY EDITION TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE EXTERNAL JOB TO L2ADMIN WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'L2ADMIN',
  GRANT_OPTION => TRUE);
END;
/
  GRANT GRANT ANY OBJECT PRIVILEGE TO L2ADMIN WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'L2ADMIN', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => TRUE);
END;
/
  GRANT DROP ANY INDEXTYPE TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY OPERATOR TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE OPERATOR TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY MATERIALIZED VIEW TO L2ADMIN WITH ADMIN OPTION;
  GRANT GRANT ANY PRIVILEGE TO L2ADMIN WITH ADMIN OPTION;
  GRANT ANALYZE ANY TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY PROCEDURE TO L2ADMIN WITH ADMIN OPTION;
  GRANT AUDIT ANY TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE PUBLIC DATABASE LINK TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY SYNONYM TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE SYNONYM TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY INDEX TO L2ADMIN WITH ADMIN OPTION;
  GRANT UPDATE ANY TABLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT SELECT ANY TABLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT LOCK ANY TABLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY TABLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE TABLESPACE TO L2ADMIN WITH ADMIN OPTION;
  GRANT RESTRICTED SESSION TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY CUBE TO L2ADMIN WITH ADMIN OPTION;
  GRANT SELECT ANY CUBE DIMENSION TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE CUBE DIMENSION TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY MINING MODEL TO L2ADMIN WITH ADMIN OPTION;
  GRANT ADMINISTER ANY SQL TUNING SET TO L2ADMIN WITH ADMIN OPTION;
  GRANT SELECT ANY TRANSACTION TO L2ADMIN WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'L2ADMIN',
  GRANT_OPTION => TRUE);
END;
/
  GRANT DEBUG CONNECT SESSION TO L2ADMIN WITH ADMIN OPTION;
  GRANT UNDER ANY TABLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT EXECUTE ANY INDEXTYPE TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY INDEXTYPE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY INDEXTYPE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE LIBRARY TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY TYPE TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY TRIGGER TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY TRIGGER TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY PROCEDURE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE PROCEDURE TO L2ADMIN WITH ADMIN OPTION;
  GRANT FORCE TRANSACTION TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP PUBLIC DATABASE LINK TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY CLUSTER TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE CLUSTER TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY TABLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ROLLBACK SEGMENT TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE USER TO L2ADMIN WITH ADMIN OPTION;
  GRANT UPDATE ANY CUBE DIMENSION TO L2ADMIN WITH ADMIN OPTION;
  GRANT UPDATE ANY CUBE BUILD PROCESS TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY CUBE BUILD PROCESS TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY MINING MODEL TO L2ADMIN WITH ADMIN OPTION;
  GRANT EXECUTE ASSEMBLY TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY JOB TO L2ADMIN WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'L2ADMIN',
  GRANT_OPTION => TRUE);
END;
/
  GRANT EXPORT FULL DATABASE TO L2ADMIN WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'L2ADMIN',
  GRANT_OPTION => TRUE);
END;
/
  GRANT MERGE ANY VIEW TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY OUTLINE TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY CONTEXT TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY CONTEXT TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY DIMENSION TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY OPERATOR TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY LIBRARY TO L2ADMIN WITH ADMIN OPTION;
  GRANT EXECUTE ANY TYPE TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY DIRECTORY TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP PROFILE TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY PROCEDURE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ROLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY SEQUENCE TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY SEQUENCE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY SEQUENCE TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY CLUSTER TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY TABLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP USER TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP TABLESPACE TO L2ADMIN WITH ADMIN OPTION;
  GRANT MANAGE TABLESPACE TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER TABLESPACE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE CUBE TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY CUBE DIMENSION TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY ASSEMBLY TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY EDITION TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY EDITION TO L2ADMIN WITH ADMIN OPTION;
  GRANT MANAGE ANY FILE GROUP TO L2ADMIN WITH ADMIN OPTION;
  GRANT MANAGE FILE GROUP TO L2ADMIN WITH ADMIN OPTION;
  GRANT MANAGE SCHEDULER TO L2ADMIN WITH ADMIN OPTION;
  GRANT ADVISOR TO L2ADMIN WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'L2ADMIN',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'L2ADMIN',
  GRANT_OPTION => TRUE);
END;
/
  GRANT CREATE DIMENSION TO L2ADMIN WITH ADMIN OPTION;
  GRANT GLOBAL QUERY REWRITE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE INDEXTYPE TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER DATABASE TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY ROLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT GRANT ANY ROLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY ROLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT SELECT ANY SEQUENCE TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY INDEX TO L2ADMIN WITH ADMIN OPTION;
  GRANT ADMINISTER SQL MANAGEMENT OBJECT TO L2ADMIN WITH ADMIN OPTION;
  GRANT INSERT ANY MEASURE FOLDER TO L2ADMIN WITH ADMIN OPTION;
  GRANT DELETE ANY CUBE DIMENSION TO L2ADMIN WITH ADMIN OPTION;
  GRANT EXEMPT IDENTITY POLICY TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY SQL PROFILE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE JOB TO L2ADMIN WITH ADMIN OPTION;
  GRANT ANALYZE ANY DICTIONARY TO L2ADMIN WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'L2ADMIN',
  GRANT_OPTION => TRUE);
END;
/
  GRANT SELECT ANY DICTIONARY TO L2ADMIN WITH ADMIN OPTION;
  GRANT RESUMABLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT EXEMPT ACCESS POLICY TO L2ADMIN WITH ADMIN OPTION;
  GRANT ON COMMIT REFRESH TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY DIMENSION TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY DIRECTORY TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY MATERIALIZED VIEW TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER RESOURCE COST TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE PROFILE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE TRIGGER TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE PUBLIC SYNONYM TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY SYNONYM TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY INDEX TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ROLLBACK SEGMENT TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE SESSION TO L2ADMIN WITH ADMIN OPTION;
  GRANT AUDIT SYSTEM TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER PUBLIC DATABASE LINK TO L2ADMIN WITH ADMIN OPTION;
  GRANT DELETE ANY MEASURE FOLDER TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY MEASURE FOLDER TO L2ADMIN WITH ADMIN OPTION;
  GRANT UPDATE ANY CUBE TO L2ADMIN WITH ADMIN OPTION;
  GRANT SELECT ANY CUBE TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY CUBE DIMENSION TO L2ADMIN WITH ADMIN OPTION;
  GRANT SELECT ANY MINING MODEL TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY MINING MODEL TO L2ADMIN WITH ADMIN OPTION;
  GRANT EXECUTE ANY ASSEMBLY TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY ASSEMBLY TO L2ADMIN WITH ADMIN OPTION;
  GRANT CHANGE NOTIFICATION TO L2ADMIN WITH ADMIN OPTION;
  GRANT READ ANY FILE GROUP TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY SQL PROFILE TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY SQL PROFILE TO L2ADMIN WITH ADMIN OPTION;
  GRANT EXECUTE ANY PROGRAM TO L2ADMIN WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'L2ADMIN',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'L2ADMIN',
  GRANT_OPTION => TRUE);
END;
/
  GRANT DEBUG ANY PROCEDURE TO L2ADMIN WITH ADMIN OPTION;
  GRANT ADMINISTER DATABASE TRIGGER TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY OUTLINE TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY OUTLINE TO L2ADMIN WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'L2ADMIN',
  ADMIN_OPTION => TRUE);
END;
/
  GRANT ALTER ANY OPERATOR TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER ANY LIBRARY TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE MATERIALIZED VIEW TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY TRIGGER TO L2ADMIN WITH ADMIN OPTION;
  GRANT EXECUTE ANY PROCEDURE TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE DATABASE LINK TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY VIEW TO L2ADMIN WITH ADMIN OPTION;
  GRANT CREATE ANY VIEW TO L2ADMIN WITH ADMIN OPTION;
  GRANT DROP ANY CLUSTER TO L2ADMIN WITH ADMIN OPTION;
  GRANT BACKUP ANY TABLE TO L2ADMIN WITH ADMIN OPTION;
  GRANT BECOME USER TO L2ADMIN WITH ADMIN OPTION;
  GRANT ALTER SESSION TO L2ADMIN WITH ADMIN OPTION;
  -- 1 Tablespace Quota for L2ADMIN 
  ALTER USER L2ADMIN QUOTA UNLIMITED ON USERS;


DROP USER L2_MANAGER CASCADE;

CREATE USER L2_MANAGER
  IDENTIFIED BY L2_MANAGER
  DEFAULT TABLESPACE &TABLESPACE
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for L2_MANAGER 
  GRANT CONNECT TO L2_MANAGER;
  ALTER USER L2_MANAGER DEFAULT ROLE NONE;
  -- 2 System Privileges for L2_MANAGER 
  GRANT CREATE SESSION TO L2_MANAGER;
  GRANT SELECT ANY TABLE TO L2_MANAGER;
  -- 1 Tablespace Quota for L2_MANAGER 
  ALTER USER L2_MANAGER QUOTA UNLIMITED ON USERS;
  -- 17 Object Privileges for L2_MANAGER 
    --GRANT SELECT ON MAIN.MON_PROCESS TO L2_MANAGER;
    GRANT SELECT ON SYS.DBA_JOBS TO L2_MANAGER;
    GRANT SELECT ON SYS.DBA_JOBS_RUNNING TO L2_MANAGER;
    GRANT SELECT ON SYS.DBA_OBJECTS TO L2_MANAGER;
    GRANT SELECT ON SYS.DBA_VIEWS TO L2_MANAGER;
    GRANT SELECT ON SYS.DBA_WAITERS TO L2_MANAGER;
    GRANT SELECT ON SYS.DBMS_ALERT_INFO TO L2_MANAGER;
    GRANT EXECUTE ON SYS.DBMS_SYSTEM TO L2_MANAGER;
    GRANT SELECT ON SYS.GV_$INSTANCE TO L2_MANAGER;
    GRANT SELECT ON SYS.GV_$LOCK TO L2_MANAGER;
    GRANT SELECT ON SYS.GV_$LOCKED_OBJECT TO L2_MANAGER;
    GRANT SELECT ON SYS.GV_$SESSION TO L2_MANAGER;
    GRANT SELECT ON SYS.JOB$ TO L2_MANAGER;
    GRANT SELECT ON SYS.V_$DATABASE TO L2_MANAGER;
    GRANT SELECT ON SYS.V_$MYSTAT TO L2_MANAGER;
    GRANT SELECT ON SYS.V_$PROCESS TO L2_MANAGER;
    GRANT SELECT ON SYS.V_$SESSION TO L2_MANAGER;


DROP USER SIM_TRACK CASCADE;
  
CREATE USER SIM_TRACK
  IDENTIFIED BY SIM_TRACK
  DEFAULT TABLESPACE &TABLESPACE
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- Roles for SIM_TRACK 
  GRANT RESOURCE TO SIM_TRACK;
  GRANT CONNECT TO SIM_TRACK;
  ALTER USER SIM_TRACK DEFAULT ROLE ALL;
  GRANT UNLIMITED TABLESPACE TO SIM_TRACK;
  grant execute on sys.dbms_lock to SIM_TRACK;


DROP USER HMIUSER CASCADE;

CREATE USER HMIUSER
  IDENTIFIED BY HMIUSER
  DEFAULT TABLESPACE &TABLESPACE
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for HMIUSER 
  GRANT RESOURCE TO HMIUSER;
  GRANT CONNECT TO HMIUSER;
  ALTER USER HMIUSER DEFAULT ROLE ALL;
  -- 9 System Privileges for HMIUSER 
  GRANT DELETE ANY TABLE TO HMIUSER WITH ADMIN OPTION;
  GRANT INSERT ANY TABLE TO HMIUSER WITH ADMIN OPTION;
  GRANT SELECT ANY TABLE TO HMIUSER WITH ADMIN OPTION;
  GRANT CREATE ANY SYNONYM TO HMIUSER;
  GRANT UPDATE ANY TABLE TO HMIUSER WITH ADMIN OPTION;
  GRANT EXECUTE ANY INDEXTYPE TO HMIUSER WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO HMIUSER;
  GRANT CREATE ANY JOB TO HMIUSER WITH ADMIN OPTION;
  GRANT EXECUTE ANY PROCEDURE TO HMIUSER WITH ADMIN OPTION;
  -- 517 Object Privileges for HMIUSER 
    GRANT SELECT ON SYS.DBA_JOBS TO HMIUSER;
    GRANT SELECT ON SYS.DBA_JOBS_RUNNING TO HMIUSER;
    GRANT SELECT ON SYS.DBA_OBJECTS TO HMIUSER;
    GRANT SELECT ON SYS.DBA_VIEWS TO HMIUSER;
    GRANT SELECT ON SYS.DBA_WAITERS TO HMIUSER;
    GRANT EXECUTE ON SYS.DBMS_ALERT TO HMIUSER;
    GRANT SELECT ON SYS.DBMS_ALERT_INFO TO HMIUSER;
    GRANT EXECUTE, DEBUG ON SYS.DBMS_FLASHBACK TO HMIUSER;
    GRANT EXECUTE ON SYS.DBMS_JOB TO HMIUSER;
    GRANT EXECUTE ON SYS.DBMS_LOCK TO HMIUSER;
    GRANT EXECUTE ON SYS.DBMS_PIPE TO HMIUSER;
    GRANT EXECUTE ON SYS.DBMS_SYSTEM TO HMIUSER;
    GRANT SELECT ON SYS.GV_$INSTANCE TO HMIUSER;
    GRANT SELECT ON SYS.GV_$LOCK TO HMIUSER;
    GRANT SELECT ON SYS.GV_$LOCKED_OBJECT TO HMIUSER;
    GRANT SELECT ON SYS.GV_$SESSION TO HMIUSER;
    GRANT SELECT ON SYS.JOB$ TO HMIUSER;
    GRANT READ, WRITE ON DIRECTORY SYS.PS_EXCHANGE_DIR TO HMIUSER;
    GRANT SELECT ON SYS.V_$DATABASE TO HMIUSER;
    GRANT SELECT ON SYS.V_$MYSTAT TO HMIUSER;
    GRANT SELECT ON SYS.V_$PROCESS TO HMIUSER;
    GRANT SELECT ON SYS.V_$SESSION TO HMIUSER;
    

DROP USER HISTORY CASCADE;

CREATE USER HISTORY
  IDENTIFIED BY VALUES '6CF0FB07E58890DF'
  DEFAULT TABLESPACE MEDDATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for HISTORY 
  GRANT CONNECT TO HISTORY;
  GRANT RESOURCE TO HISTORY;
  ALTER USER HISTORY DEFAULT ROLE ALL;
  -- 1 System Privilege for HISTORY 
  GRANT UNLIMITED TABLESPACE TO HISTORY;
  -- 1 Object Privilege for HISTORY 
    GRANT EXECUTE, DEBUG ON MAIN.VARGS TO HISTORY;


DROP USER MAINTENANCE CASCADE;

CREATE USER MAINTENANCE
  IDENTIFIED BY VALUES '52AFA3A0B64F7001'
  DEFAULT TABLESPACE MEDDATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for MAINTENANCE 
  GRANT CONNECT TO MAINTENANCE;
  GRANT RESOURCE TO MAINTENANCE;
  ALTER USER MAINTENANCE DEFAULT ROLE ALL;
  -- 6 System Privileges for MAINTENANCE 
  GRANT ADMINISTER DATABASE TRIGGER TO MAINTENANCE;
  GRANT ALTER SYSTEM TO MAINTENANCE;
  GRANT CREATE ANY SYNONYM TO MAINTENANCE;
  GRANT CREATE PROCEDURE TO MAINTENANCE;
  GRANT EXECUTE ANY PROCEDURE TO MAINTENANCE;
  GRANT UNLIMITED TABLESPACE TO MAINTENANCE;
  -- 18 Object Privileges for MAINTENANCE 
    GRANT EXECUTE, DEBUG ON MAIN.VARGS TO MAINTENANCE;
    GRANT SELECT ON SYS.DBA_JOBS TO MAINTENANCE;
    GRANT SELECT ON SYS.DBA_JOBS_RUNNING TO MAINTENANCE;
    GRANT SELECT ON SYS.DBA_OBJECTS TO MAINTENANCE;
    GRANT SELECT ON SYS.DBA_VIEWS TO MAINTENANCE;
    GRANT SELECT ON SYS.DBA_WAITERS TO MAINTENANCE;
    GRANT SELECT ON SYS.DBMS_ALERT_INFO TO MAINTENANCE;
    GRANT EXECUTE ON SYS.DBMS_SYSTEM TO MAINTENANCE;
    GRANT SELECT ON SYS.GV_$INSTANCE TO MAINTENANCE;
    GRANT SELECT ON SYS.GV_$LOCK TO MAINTENANCE;
    GRANT SELECT ON SYS.GV_$LOCKED_OBJECT TO MAINTENANCE;
    GRANT SELECT ON SYS.GV_$SESSION TO MAINTENANCE;
    GRANT SELECT ON SYS.JOB$ TO MAINTENANCE;
    GRANT SELECT ON SYS.V_$DATABASE TO MAINTENANCE;
    GRANT SELECT ON SYS.V_$MYSTAT TO MAINTENANCE;
    GRANT SELECT ON SYS.V_$PROCESS TO MAINTENANCE;
    GRANT SELECT ON SYS.V_$SESSION TO MAINTENANCE;
    GRANT EXECUTE, DEBUG ON MAIN.VARGS TO MAINTENANCE;
    

DROP USER RSH CASCADE;

CREATE USER RSH
  IDENTIFIED BY VALUES '54871CF7333F3D67'
  DEFAULT TABLESPACE MEDDATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for RSH 
  GRANT CONNECT TO RSH;
  GRANT RESOURCE TO RSH;
  ALTER USER RSH DEFAULT ROLE ALL;
  -- 6 System Privileges for RSH 
  GRANT ADMINISTER DATABASE TRIGGER TO RSH;
  GRANT ALTER SYSTEM TO RSH;
  GRANT CREATE ANY SYNONYM TO RSH;
  GRANT CREATE PROCEDURE TO RSH;
  GRANT EXECUTE ANY PROCEDURE TO RSH;
  GRANT UNLIMITED TABLESPACE TO RSH;
  -- 24 Object Privileges for RSH 
    GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON MAIN.GACS_COM_STATUS TO RSH;
    GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON MAIN.GACS_LOGGING TO RSH;
    GRANT EXECUTE ON MAIN.MON TO RSH;
    GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON MAIN.PTR_MESSAGE_DEFINITION TO RSH;
    GRANT ALTER, SELECT ON MAIN.PTR_MESS_NO TO RSH;
    GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON MAIN.PTR_RECEIVED_MESSAGE TO RSH;
    GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON MAIN.PTR_SENT_MESSAGE TO RSH;
    GRANT EXECUTE, DEBUG ON MAIN.VARGS TO RSH;
    GRANT SELECT ON SYS.DBA_JOBS TO RSH;
    GRANT SELECT ON SYS.DBA_JOBS_RUNNING TO RSH;
    GRANT SELECT ON SYS.DBA_OBJECTS TO RSH;
    GRANT SELECT ON SYS.DBA_VIEWS TO RSH;
    GRANT SELECT ON SYS.DBA_WAITERS TO RSH;
    GRANT SELECT ON SYS.DBMS_ALERT_INFO TO RSH;
    GRANT EXECUTE ON SYS.DBMS_SYSTEM TO RSH;
    GRANT SELECT ON SYS.GV_$INSTANCE TO RSH;
    GRANT SELECT ON SYS.GV_$LOCK TO RSH;
    GRANT SELECT ON SYS.GV_$LOCKED_OBJECT TO RSH;
    GRANT SELECT ON SYS.GV_$SESSION TO RSH;
    GRANT SELECT ON SYS.JOB$ TO RSH;
    GRANT SELECT ON SYS.V_$DATABASE TO RSH;
    GRANT SELECT ON SYS.V_$MYSTAT TO RSH;
    GRANT SELECT ON SYS.V_$PROCESS TO RSH;
    GRANT SELECT ON SYS.V_$SESSION TO RSH;



DROP USER PRODUCTION CASCADE;

CREATE USER PRODUCTION
  IDENTIFIED BY VALUES '77019D0FE6E69024'
  DEFAULT TABLESPACE MEDDATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for PRODUCTION 
  GRANT CONNECT TO PRODUCTION;
  GRANT RESOURCE TO PRODUCTION;
  ALTER USER PRODUCTION DEFAULT ROLE ALL;
  -- 6 System Privileges for PRODUCTION 
  GRANT ADMINISTER DATABASE TRIGGER TO PRODUCTION;
  GRANT ALTER SYSTEM TO PRODUCTION;
  GRANT CREATE ANY SYNONYM TO PRODUCTION;
  GRANT CREATE PROCEDURE TO PRODUCTION;
  GRANT EXECUTE ANY PROCEDURE TO PRODUCTION;
  GRANT UNLIMITED TABLESPACE TO PRODUCTION;
 
  
    GRANT EXECUTE, DEBUG ON MAIN.VARGS TO PRODUCTION;
    GRANT SELECT ON SYS.DBA_JOBS TO PRODUCTION;
    GRANT SELECT ON SYS.DBA_JOBS_RUNNING TO PRODUCTION;
    GRANT SELECT ON SYS.DBA_OBJECTS TO PRODUCTION;
    GRANT SELECT ON SYS.DBA_VIEWS TO PRODUCTION;
    GRANT SELECT ON SYS.DBA_WAITERS TO PRODUCTION;
    GRANT SELECT ON SYS.DBMS_ALERT_INFO TO PRODUCTION;
    GRANT EXECUTE ON SYS.DBMS_SYSTEM TO PRODUCTION;
    GRANT SELECT ON SYS.GV_$INSTANCE TO PRODUCTION;
    GRANT SELECT ON SYS.GV_$LOCK TO PRODUCTION;
    GRANT SELECT ON SYS.GV_$LOCKED_OBJECT TO PRODUCTION;
    GRANT SELECT ON SYS.GV_$SESSION TO PRODUCTION;
    GRANT SELECT ON SYS.JOB$ TO PRODUCTION;
    GRANT SELECT ON SYS.V_$DATABASE TO PRODUCTION;
    GRANT SELECT ON SYS.V_$MYSTAT TO PRODUCTION;
    GRANT SELECT ON SYS.V_$PROCESS TO PRODUCTION;
    GRANT SELECT ON SYS.V_$SESSION TO PRODUCTION;